venue_task :
    description : >
      "Find a venue in {event_city} "
      "that meets criteria for {event_topic}."
    expected_output : >
      "All the details of a specifically chosen"
      "venue you found to accommodate the event."
    agent : venue_coordinator

logistics_task :
    description : >
      "Coordinate catering and "
      "equipment for an event "
      "with {expected_participants} participants "
      "on {tentative_date}."
    expected_output : >
      "Confirmation of all logistics arrangements "
      "including catering and equipment setup."
    agent : logistics_manager

marketing_task :
    description : >
      "Promote the {event_topic} "
      "aiming to engage at least"
      "{expected_participants} potential attendees."
    expected_output : >
      "Report on marketing activities "
      "and attendee engagement formatted as markdown."
    agent : marketing_communications_agent
